### ISSUE TITLE
iOS 11, iPhone 7 Simulator, Xcode Version 9.0 beta 6 (9M214v) - Initial selected values not aligned.

### ISSUE THREAD

**Issue by neilt** [filipealva/PickerView#30]
Selected values don't line up.  Not sure if it is the PickerView or Apple, but here it is, none-the-less.

![screen shot 2017-08-29 at 4 22 32 pm](https://user-images.githubusercontent.com/1809796/29844962-be940b32-8cd6-11e7-9d4b-04b0c5e8bff0.png)

When I click on the number 9 in the first picker it does this.

![screen shot 2017-08-29 at 4 30 40 pm](https://user-images.githubusercontent.com/1809796/29845172-822e9670-8cd7-11e7-92b9-52b2c74ac805.png)

If i scroll all pickers to the top (0) then back to the correct value, then it looks correct.

![screen shot 2017-08-29 at 4 35 26 pm](https://user-images.githubusercontent.com/1809796/29845350-19bdb804-8cd8-11e7-80b4-d776632ed49e.png)

Thereafter it seems to work correctly.

**Comment by luisfsresende** [comment]
Have the same problem. Any plans to look into this?

**Comment by neilt** [comment]
Can confirm this is still a problem with Xcode 9 GM. The following test results were from an application compiled with the Xcode 9 GM SDK.

1. iPhone SE Hardware iOS 10.3.3, does NOT exhibit the problem.
2. iPhone SE Simulator iOS 10.3.1, does NOT exhibit the problem.
3. iPhone SE Simulator iOS 11.0 does exhibit the problem.

From our limited testing it appears to be an iOS issue and not an SDK issue.  We anticipate this will effect existing users upgrading to iOS 11.

**Comment by filipealva** [comment]
Hey guys,

Thanks for reporting. 

I'm on it. As soon as I fix it I'll release a new version of PickerView.

**Comment by filipealva** [comment]
Update: It looks like the problem is with the initial calculations of the tableView's content size property. 

Something behind the sdk scenes might have changed a bit and is causing it to calculate the content size wrong despite there is no change to the code base. 

It's not fixed yet but I'm working to fix and release a new version as soon as possible.

**Comment by AlexanderPravodudov** [comment]
Hi guys, have the same issues, the main problem it's xcode version 9.0 you should use actual version of xcode 8.3.3 fоr example, don't use beta version. When i build my project from xcode 8.3.3 everything is ok, but if i try do the same from xcode 9.0 problem come back.

**Comment by filipealva** [comment]
It looks like I managed to fix it! 🤘 

I'll soon release a new version of PickerView with this fix. If you guys want to take a look on the fixed version please look into [this branch](https://github.com/filipealva/PickerView/tree/fix/wrong-initial-scrolling).

The solution: In iOS 11 the UITableView uses the value of `estimatedRowHeight` (even if you didn't set it) to calculate the `contentSize`. I was not setting any value to this property and because of it the `contentSize`was being calculated wrong by the UITableVIew. Once the user scrolls it the UITableVIew seems to detect that the contentSize is not fitting the real content and then calls the delegate method `heightForRowAtIndexPath` to fix the `contentSize`. 

By setting all the "estimated" properties of the UITableVIew to zero we cancel this new behavior of iOS 11 and the UITableVIew look directly into `heightForRowAtIndexPath` to calculate the `contentSize`.

**Comment by neilt** [comment]
I can confirm that your fix does indeed fix the problem in iOS 11 and does not cause any additional problems with iOS 10.3.3, which continues to work correctly.

Thank you.

**Comment by filipealva** [comment]
![0.3.2](https://user-images.githubusercontent.com/6117280/30946472-aafa230c-a3da-11e7-9fae-d43af76752e3.png)

Hey guys,

The new version has been released. Please let me know if everything is working.

**Comment by neilt** [comment]
Working for me, thanks.
