### ISSUE TITLE
Unexpected error on xcode 9 and ios 11.

### ISSUE THREAD

**Issue by kunass2** [filipealva/PickerView#32]
<img width="1218" alt="screen shot 2017-09-27 at 14 47 26" src="https://user-images.githubusercontent.com/9480650/30914156-e92aa4a0-a392-11e7-8748-03858e04ad63.png">

What can I do with this?;-)

**Comment by fennoma-dfelix** [comment]
Have you tried the suggestion of adding @objc?

**Comment by filipealva** [comment]
@kunass2 did you converted the project to Swift 4? If only happens with me if I do convert it to Swift 4 using the migration assistant of Xcode.

Since you can have it working on your Swift 4 project even without converting I would not recommend to convert the source code of PickerView to Swift 4, if you need to do that you'll have to deal with some issues caused by the migration assistant such as @objc notations removals

Another thing that maybe is causing it is if you're building the project with Xcode 8 and Xcode 9 without cleaning the `DerivatedData` folder, I had some weird issues when I did it.

**Comment by neilt** [comment]
I had the same problem when using installing via Podfile in Swift 4 project.  The pod build target is getting set to Swift 4 by default.  I had to manually change it back to Swift 3.2 to get my project to build.

To see this problem try to add PickerView pod to any swift 4 project.

**Comment by filipealva** [comment]
Sorry guys, I did not tried to install in a Swift 4 project. Thanks @neilt I was able to reproduce it after your comment.

Just released version `0.3.3` compatible with Swift 4 projects.

Let me know if everything is ok.

![captura de tela 2017-10-03 as 10 46 04](https://user-images.githubusercontent.com/6117280/31128495-5ec2dcb6-a828-11e7-9639-6ad974f5a0cd.png)

**Comment by kunass2** [comment]
Nice;) I will try it within houirs and let you know if everything is alright;-) good job

**Comment by neilt** [comment]
Seems to work here!

**Comment by kunass2** [comment]
Works great;) 👍

**Comment by filipealva** [comment]
thanks guys
