### ISSUE TITLE
Empty, selectable entry is shown on iOS 10

### ISSUE THREAD

**Issue by Mershl** [filipealva/PickerView#48]
Pod used: - PickerView (0.3.4)

We've integrated the example project and tested it on iOS 10 and iOS12. On iOS 10 an empty entry is shown before the first entry and it's selectable. I suspect this in an layout issue. Here's a screencast of the issue in action:

![kapture 2018-10-11 at 11 33 07](https://user-images.githubusercontent.com/520251/46795082-8572cc80-cd49-11e8-9a86-50cae6f1de55.gif)

**Comment by filipealva** [comment]
Hi @Mershl,

Sorry about the delay. I could reproduce this issue, the problem is that the `PickerView` is built on top of a `UITableView` and it can't have its contentInset affected by anything. 

You probably have set this view controller to `automaticallyAdjustsContentInset`, to fix this behavior you just need to set it to false or uncheck the option on your storyboard file.

You can see the option on [this answer](https://stackoverflow.com/a/22022366/5241106).
